import 'models.dart';

class DemoData {
  static const heroFood =
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200';
  static const produceMarket =
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=900';
  static const equipmentPhoto =
      'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=900';
  static const bowlPhoto =
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=900';
  static const yogurtPhoto =
      'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=900';

  static const initialProfile = DemoProfile(
    name: 'Lan Anh',
    age: 28,
    gender: Gender.female,
    heightCm: 165,
    weightKg: 62,
    targetWeightKg: 55,
    goal: GoalType.loseWeight,
    activityLevel: ActivityLevel.moderate,
    schedule: 'Văn phòng 8h-17h',
    dietaryRestrictions: ['Không lactose'],
    allergies: [],
    healthConditions: [],
    trainingFrequency: '3 lần/tuần',
    focusAreas: ['Bụng', 'Chân', 'Toàn Thân'],
    preferredActivities: ['Tập thể dục tại nhà', 'HIIT', 'Phục hồi'],
    mealBudget: 'Cân bằng',
    cookingTime: '15-30 phút',
    nutritionPriorities: ['Giàu protein', 'Món Việt', 'Meal prep'],
    plan: SubscriptionPlan.free,
    subscriptionMonths: 0,
    tokenBalance: 120,
    tokenEarned: 120,
  );

  static const weightEntries = [
    WeightEntry(label: '21/03', weight: 64.5),
    WeightEntry(label: '22/03', weight: 64.0),
    WeightEntry(label: '23/03', weight: 63.5),
    WeightEntry(label: '24/03', weight: 63.0),
    WeightEntry(label: '25/03', weight: 62.8),
    WeightEntry(label: '26/03', weight: 62.4),
    WeightEntry(label: '27/03', weight: 62.0),
  ];

  static const dashboardInsights = [
    InsightItem(
      title: 'Tiến độ tuyệt vời! 🎉',
      message:
          'Cân nặng đang giảm đều 2.9kg mỗi tuần với lịch ăn và tập hiện tại.',
      accent: 'success',
    ),
    InsightItem(
      title: 'Macro hôm nay cân bằng',
      message: 'Protein đủ tốt để giữ cơ. Chỉ cần thêm chất xơ vào bữa chiều.',
      accent: 'emerald',
    ),
    InsightItem(
      title: 'AI gợi ý',
      message: 'Tăng 10 phút cardio nhẹ sau bữa tối để đẩy nhanh tiến trình.',
      accent: 'violet',
    ),
  ];

  static const todayMeals = [
    MealItem(
      id: 'meal-log-1',
      nameVi: 'Phở bò',
      slotLabel: '🌅 Sáng',
      calories: 380,
      protein: 28,
      carbs: 48,
      fat: 8,
      imageUrl: heroFood,
      ingredients: ['Bánh phở', 'Thịt bò', 'Giá đỗ', 'Hành lá'],
    ),
    MealItem(
      id: 'meal-log-2',
      nameVi: 'Cơm gà',
      slotLabel: '☀️ Trưa',
      calories: 520,
      protein: 38,
      carbs: 58,
      fat: 14,
      imageUrl: bowlPhoto,
      ingredients: ['Cơm', 'Thịt gà', 'Dưa leo', 'Canh rau'],
    ),
    MealItem(
      id: 'meal-log-3',
      nameVi: 'Ức gà & cơm gạo lứt',
      slotLabel: '🌙 Tối',
      calories: 460,
      protein: 40,
      carbs: 48,
      fat: 8,
      imageUrl: yogurtPhoto,
      ingredients: ['Ức gà', 'Gạo lứt', 'Bông cải', 'Sốt chanh'],
    ),
  ];

  static const products = [
    Product(
      id: 'p1',
      nameVi: 'Rau củ tươi hỗn hợp',
      categoryId: 'vegetable',
      unit: '500g',
      priceK: 45,
      imageUrl: produceMarket,
      hot: true,
    ),
    Product(
      id: 'p2',
      nameVi: 'Súp lơ xanh',
      categoryId: 'vegetable',
      unit: '300g',
      priceK: 35,
      imageUrl: produceMarket,
      hot: true,
    ),
    Product(
      id: 'p3',
      nameVi: 'Rau bina',
      categoryId: 'vegetable',
      unit: '250g',
      priceK: 25,
      imageUrl: produceMarket,
      hot: false,
    ),
    Product(
      id: 'p4',
      nameVi: 'Ức gà',
      categoryId: 'protein',
      unit: '500g',
      priceK: 85,
      imageUrl: bowlPhoto,
      hot: false,
    ),
    Product(
      id: 'p5',
      nameVi: 'Phi lê cá hồi',
      categoryId: 'protein',
      unit: '300g',
      priceK: 180,
      imageUrl: bowlPhoto,
      hot: true,
    ),
    Product(
      id: 'p6',
      nameVi: 'Yến mạch',
      categoryId: 'grain',
      unit: '500g',
      priceK: 55,
      imageUrl: yogurtPhoto,
      hot: false,
    ),
    Product(
      id: 'p7',
      nameVi: 'Chuối',
      categoryId: 'fruit',
      unit: '1kg',
      priceK: 25,
      imageUrl: heroFood,
      hot: false,
    ),
    Product(
      id: 'p8',
      nameVi: 'Sữa chua Hy Lạp',
      categoryId: 'dairy',
      unit: '500g',
      priceK: 45,
      imageUrl: yogurtPhoto,
      hot: true,
    ),
    Product(
      id: 'p9',
      nameVi: 'Bột protein',
      categoryId: 'supplement',
      unit: '1kg',
      priceK: 450,
      imageUrl: equipmentPhoto,
      hot: false,
    ),
    Product(
      id: 'p10',
      nameVi: 'Thảm yoga',
      categoryId: 'equipment',
      unit: '1 cái',
      priceK: 250,
      imageUrl: equipmentPhoto,
      hot: false,
    ),
    Product(
      id: 'p11',
      nameVi: 'Dây kháng lực',
      categoryId: 'equipment',
      unit: 'Bộ 5 dây',
      priceK: 180,
      imageUrl: equipmentPhoto,
      hot: true,
    ),
    Product(
      id: 'p12',
      nameVi: 'Bình nước thể thao',
      categoryId: 'equipment',
      unit: '1L',
      priceK: 85,
      imageUrl: equipmentPhoto,
      hot: false,
    ),
    Product(
      id: 'p13',
      nameVi: 'Trứng gà ta',
      categoryId: 'protein',
      unit: '10 quả',
      priceK: 40,
      imageUrl: bowlPhoto,
      hot: true,
    ),
    Product(
      id: 'p14',
      nameVi: 'Đậu phụ hữu cơ',
      categoryId: 'protein',
      unit: '400g',
      priceK: 28,
      imageUrl: bowlPhoto,
      hot: false,
    ),
    Product(
      id: 'p15',
      nameVi: 'Hạt chia',
      categoryId: 'supplement',
      unit: '200g',
      priceK: 65,
      imageUrl: yogurtPhoto,
      hot: true,
    ),
    Product(
      id: 'p16',
      nameVi: 'Khoai lang tím',
      categoryId: 'vegetable',
      unit: '1kg',
      priceK: 30,
      imageUrl: produceMarket,
      hot: false,
    ),
    Product(
      id: 'p17',
      nameVi: 'Bơ hạt điều',
      categoryId: 'supplement',
      unit: '250g',
      priceK: 95,
      imageUrl: yogurtPhoto,
      hot: true,
    ),
    Product(
      id: 'p18',
      nameVi: 'Cá ngừ đóng hộp',
      categoryId: 'protein',
      unit: '3 hộp 185g',
      priceK: 55,
      imageUrl: bowlPhoto,
      hot: false,
    ),
    Product(
      id: 'p19',
      nameVi: 'Xà lách xoăn',
      categoryId: 'vegetable',
      unit: '300g',
      priceK: 22,
      imageUrl: produceMarket,
      hot: false,
    ),
    Product(
      id: 'p20',
      nameVi: 'Vitamin D3 + K2',
      categoryId: 'supplement',
      unit: '60 viên',
      priceK: 180,
      imageUrl: yogurtPhoto,
      hot: false,
    ),
    Product(
      id: 'p21',
      nameVi: 'Cân điện tử thông minh',
      categoryId: 'equipment',
      unit: '1 cái',
      priceK: 320,
      imageUrl: equipmentPhoto,
      hot: true,
    ),
    Product(
      id: 'p22',
      nameVi: 'Gạo lứt huyết rồng',
      categoryId: 'grain',
      unit: '1kg',
      priceK: 38,
      imageUrl: heroFood,
      hot: false,
    ),
    Product(
      id: 'p23',
      nameVi: 'Xoài cát Hòa Lộc',
      categoryId: 'fruit',
      unit: '1kg',
      priceK: 45,
      imageUrl: heroFood,
      hot: true,
    ),
    Product(
      id: 'p24',
      nameVi: 'Collagen peptide',
      categoryId: 'supplement',
      unit: '200g bột',
      priceK: 290,
      imageUrl: yogurtPhoto,
      hot: false,
    ),
  ];

  static const categories = [
    ('all', 'Tất cả'),
    ('vegetable', 'Rau củ'),
    ('protein', 'Protein'),
    ('grain', 'Ngũ cốc'),
    ('fruit', 'Trái cây'),
    ('dairy', 'Sữa'),
    ('supplement', 'TPCN'),
    ('equipment', 'Đồ tập'),
  ];

  static const recentOrders = [
    OrderSummary(
      id: 'ODR-1024',
      dateLabel: '20/03/2026',
      itemCount: 1,
      totalK: 250,
      statusLabel: 'Đã giao',
    ),
  ];

  static List<MealPlanDay> mealPlan({required int totalDays}) {
    const templates = [
      [
        MealItem(
          id: 'bm1',
          nameVi: 'Phở bò',
          slotLabel: '🌅 Sáng',
          calories: 380,
          protein: 28,
          carbs: 48,
          fat: 8,
          imageUrl: heroFood,
          ingredients: ['Bánh phở', 'Thịt bò', 'Giá đỗ', 'Hành lá'],
        ),
        MealItem(
          id: 'lm1',
          nameVi: 'Cơm sườn nướng',
          slotLabel: '☀️ Trưa',
          calories: 580,
          protein: 35,
          carbs: 62,
          fat: 18,
          imageUrl: bowlPhoto,
          ingredients: ['Cơm', 'Sườn nướng', 'Rau sống', 'Nước mắm'],
        ),
        MealItem(
          id: 'dm1',
          nameVi: 'Cá hấp & rau luộc',
          slotLabel: '🌙 Tối',
          calories: 420,
          protein: 36,
          carbs: 38,
          fat: 10,
          imageUrl: bowlPhoto,
          ingredients: ['Cá hấp', 'Rau luộc', 'Gạo lứt', 'Canh rau'],
        ),
        MealItem(
          id: 'sm1',
          nameVi: 'Trái cây tươi',
          slotLabel: '🍎 Phụ',
          calories: 120,
          protein: 2,
          carbs: 28,
          fat: 0,
          imageUrl: heroFood,
          ingredients: ['Chuối', 'Táo', 'Cam'],
        ),
      ],
      [
        MealItem(
          id: 'bm2',
          nameVi: 'Cháo gà',
          slotLabel: '🌅 Sáng',
          calories: 320,
          protein: 22,
          carbs: 42,
          fat: 6,
          imageUrl: bowlPhoto,
          ingredients: ['Gạo', 'Thịt gà', 'Gừng', 'Hành lá'],
        ),
        MealItem(
          id: 'lm2',
          nameVi: 'Bún thịt nướng',
          slotLabel: '☀️ Trưa',
          calories: 480,
          protein: 32,
          carbs: 54,
          fat: 14,
          imageUrl: heroFood,
          ingredients: ['Bún', 'Thịt nướng', 'Rau sống', 'Đậu phộng'],
        ),
        MealItem(
          id: 'dm2',
          nameVi: 'Đậu hũ xào rau',
          slotLabel: '🌙 Tối',
          calories: 380,
          protein: 22,
          carbs: 42,
          fat: 14,
          imageUrl: bowlPhoto,
          ingredients: ['Đậu hũ', 'Rau xào', 'Cơm gạo', 'Tỏi'],
        ),
        MealItem(
          id: 'sm2',
          nameVi: 'Sữa chua Hy Lạp',
          slotLabel: '🍎 Phụ',
          calories: 150,
          protein: 15,
          carbs: 12,
          fat: 4,
          imageUrl: yogurtPhoto,
          ingredients: ['Sữa chua', 'Hạt chia'],
        ),
      ],
      [
        MealItem(
          id: 'bm3',
          nameVi: 'Bánh mì gà',
          slotLabel: '🌅 Sáng',
          calories: 420,
          protein: 25,
          carbs: 52,
          fat: 12,
          imageUrl: heroFood,
          ingredients: ['Bánh mì', 'Thịt gà', 'Rau củ', 'Pate'],
        ),
        MealItem(
          id: 'lm3',
          nameVi: 'Cơm gà',
          slotLabel: '☀️ Trưa',
          calories: 520,
          protein: 38,
          carbs: 58,
          fat: 14,
          imageUrl: bowlPhoto,
          ingredients: ['Cơm', 'Thịt gà', 'Canh', 'Dưa leo'],
        ),
        MealItem(
          id: 'dm3',
          nameVi: 'Ức gà & cơm gạo lứt',
          slotLabel: '🌙 Tối',
          calories: 460,
          protein: 40,
          carbs: 48,
          fat: 8,
          imageUrl: yogurtPhoto,
          ingredients: ['Ức gà', 'Cơm gạo lứt', 'Rau củ', 'Chanh'],
        ),
        MealItem(
          id: 'sm3',
          nameVi: 'Hạt dinh dưỡng',
          slotLabel: '🍎 Phụ',
          calories: 180,
          protein: 6,
          carbs: 8,
          fat: 14,
          imageUrl: yogurtPhoto,
          ingredients: ['Hạnh nhân', 'Óc chó', 'Hạt điều'],
        ),
      ],
    ];

    return List.generate(totalDays, (index) {
      final template = templates[index % templates.length];
      return MealPlanDay(dayNumber: index + 1, meals: template);
    });
  }

  static List<WorkoutDay> workoutPlan({required int totalDays}) {
    const templates = [
      WorkoutDay(
        dayNumber: 1,
        focusVi: 'Toàn thân',
        exercises: [
          WorkoutExercise(
            id: 'wx1',
            nameVi: 'Chống đẩy',
            description: 'Chống đẩy tư thế chuẩn, siết core nhẹ.',
            sets: 3,
            reps: '10-15',
            caloriesBurned: 50,
          ),
          WorkoutExercise(
            id: 'wx2',
            nameVi: 'Squat',
            description: 'Squat với trọng lượng cơ thể, xuống sâu vừa phải.',
            sets: 3,
            reps: '15-20',
            caloriesBurned: 60,
          ),
          WorkoutExercise(
            id: 'wx3',
            nameVi: 'Plank',
            description: 'Giữ core và lưng trung lập.',
            sets: 3,
            reps: '45s',
            caloriesBurned: 40,
          ),
          WorkoutExercise(
            id: 'wx4',
            nameVi: 'Lunge',
            description: 'Mỗi chân 12 reps, nhịp chậm và kiểm soát.',
            sets: 3,
            reps: '12/chân',
            caloriesBurned: 50,
          ),
          WorkoutExercise(
            id: 'wx5',
            nameVi: 'Gập bụng',
            description: 'Siết bụng, tránh kéo cổ.',
            sets: 3,
            reps: '20',
            caloriesBurned: 30,
          ),
        ],
      ),
      WorkoutDay(
        dayNumber: 2,
        focusVi: 'Cardio',
        exercises: [
          WorkoutExercise(
            id: 'wy1',
            nameVi: 'Chạy bộ',
            description: 'Chạy bộ nhịp vừa trong nhà hoặc ngoài trời.',
            durationMinutes: 30,
            caloriesBurned: 300,
          ),
          WorkoutExercise(
            id: 'wy2',
            nameVi: 'Burpees',
            description: 'Toàn thân, nhịp ổn định, nghỉ ngắn giữa hiệp.',
            sets: 3,
            reps: '10',
            caloriesBurned: 80,
          ),
          WorkoutExercise(
            id: 'wy3',
            nameVi: 'Leo núi',
            description: 'Thực hiện nhanh, giữ vai ổn định.',
            sets: 3,
            reps: '30s',
            caloriesBurned: 60,
          ),
        ],
      ),
      WorkoutDay(
        dayNumber: 3,
        focusVi: 'Sức mạnh',
        exercises: [
          WorkoutExercise(
            id: 'wz1',
            nameVi: 'Squat',
            description: 'Tăng nhịp trong 2 hiệp cuối.',
            sets: 4,
            reps: '12-15',
            caloriesBurned: 75,
          ),
          WorkoutExercise(
            id: 'wz2',
            nameVi: 'Chống đẩy nghiêng',
            description: 'Biến thể dễ hơn nếu cần giữ kỹ thuật.',
            sets: 4,
            reps: '10-12',
            caloriesBurned: 55,
          ),
          WorkoutExercise(
            id: 'wz3',
            nameVi: 'Plank cạnh',
            description: 'Giữ mỗi bên 30 giây.',
            sets: 3,
            reps: '30s/bên',
            caloriesBurned: 45,
          ),
          WorkoutExercise(
            id: 'wz4',
            nameVi: 'Nhảy dây',
            description: 'Tăng nhịp tim nhanh và đều.',
            durationMinutes: 15,
            caloriesBurned: 180,
          ),
        ],
      ),
      WorkoutDay(
        dayNumber: 4,
        focusVi: 'Core & Dẻo dai',
        exercises: [
          WorkoutExercise(
            id: 'wa1',
            nameVi: 'Yoga flow',
            description: 'Chuỗi yoga nhẹ giúp mở hông và vai.',
            durationMinutes: 20,
            caloriesBurned: 80,
          ),
          WorkoutExercise(
            id: 'wa2',
            nameVi: 'Giãn cơ',
            description: 'Giãn cơ toàn thân sau khi vận động.',
            durationMinutes: 15,
            caloriesBurned: 40,
          ),
          WorkoutExercise(
            id: 'wa3',
            nameVi: 'Plank',
            description: 'Giữ 3 hiệp ngắn để siết core.',
            sets: 3,
            reps: '30s',
            caloriesBurned: 40,
          ),
        ],
      ),
    ];

    return List.generate(totalDays, (index) {
      final template = templates[index % templates.length];
      return WorkoutDay(
        dayNumber: index + 1,
        focusVi: template.focusVi,
        exercises: template.exercises,
      );
    });
  }
}
